#
name: Build & Push

# This workflow runs when any of the following occur:
# - A push is made to a branch called `main` or `seed`
# - A tag starting with "v" is created
# - A pull request is created or updated
on:
  push:
    branches:
      - main
      - seed
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: zabbix-proxy
#
jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          mode: build
          load-mode: strict
      - name: Some other action
        run: |
          echo "Zabbix Version: ${{ env.ZABBIX_VERSION }}"
      - name: Build image
        run: docker build --build-arg ZABBIX_VERSION=${{ env.ZABBIX_VERSION }} . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        #
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # This strips the git ref prefix from the version.
          echo IMAGE_ID=$IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

          docker tag $IMAGE_NAME $IMAGE_ID:${{ env.ZABBIX_VERSION }}
          docker push $IMAGE_ID:${{ env.ZABBIX_VERSION }}
